const message = {

	UNREGISTRATION 	: {'success':false,'message':'Try again Something wrong'},
	SOMETHINGWRONG 	: {'success':false,'message':'Something went wrong'},
	ALREADYUSE 		: {"success":false,"message":'Sorry, this user is already in use'},
	PARAMETES 		: {"success":false,"message":'Give correct parameters'},
	RESETTOKEN 		: {"success":false,"message":'Reset token required'},
	FILEDS  		: {"success":false,"message":'Fill all fields'},
	ERROR   		: {"success":false,"message":'Error'},
	INVALIDEMAIL	: {"success":false,'message':'Invalid Email Id'},
	INVALIDRESETTOKEN: {"success":false,'message':'Invalid Reset Token'},
	PASSWORD    	: {'success':false,'message':"Incorrect Password"},
	USERCREATE    	: {'success':false,'message':"Your account is not activated by admin"},
	ACCOUNT 	   	: {'success':false,'message':"Could not find your account"},
	NOTPERMISSION  	: {'success':false,'message':"You have not permission"},
	CORRECTSTATUS   : {'success':false,'message':"Give correct status name"},
	DATANOTFOUND    : {'success':true,'message':"Data not found"},
	NOTACTIVEACCOUNT: {'success':false,'message':"User not activated"},
	USERPROFILE 	: {'success':false,'message':'Profile not found'},
	NOTAPPLICATION  : {'success':false,'message':"Not created application"},
	NOTUPDATE		: {'success':false,'message':"Not update profile "},
	NOTCOUNTIESLIST	: {'success':false,'message':"Not available countries list "},
	APPLICATION		: {"success":false,"message":'Sorry, this application is already in use'},
	PASSWORDNOTGEN	: {"success":false,"message":'password not generate'},
	NOTDISAPPROVEUSER:{'success':false,'message':"User not deleted"},
	ALREADYDEL		: {'success':false,'message':"Already deleted"},
	EMPTY 	        : {'success':false,'message':'Empty'},
	PERMISSIONERROR : {'success':false,'message':"you don't have permission"},
	NOTCREATED 	    : {'success':false,'message':'Not created'},
	NOTUPDATED 	    : {'success':false,'message':'Not updated'},
	ALREADYEXISTS 	: {'success':false,'message':'Already exists'},
	NORDELETED     	: {'success':false,'message':'Can not deleted'},
	IDNOTEXISTS     : {'success':false,'message':'Id not found'},
	ACCOUNTNOTACTIVE: {'success':false,'message': "User not activated for this application"},
	USERNOTFOUND 	: {'success':false,'message': "User not found"},

	//======================== true ====================================


	DISAPPROVEUSER  	: {'success':true,'message': "User disapprove sucessfully"},
	ADMINAPPROVE    	: {'success':true,'message': "Admin approved sucessfully"},
	ADMINDISAPPROVE     : {'success':true,'message': "Admin disapproved sucessfully"},
	ACTIVEACCOUNT   	: {'success':true,'message': "User activated sucessfully"},
	USERCREATE 			: {'success':true,'message': "User created successfully"},
	REGISTRATION 		: {'success':true,'message':'Registration sucessfully'},
	CREATED 	    	: {'success':true,'message':'Created sucessfully'},
	PROFILEUPDATE 		: {'success':true,'message':'Profile updated sucessfully'},
	USERUPDATE			: {'success':true,'message':'User details udpated successfully'},
	CHANGEPASSWORD 		: {'success':true,'message':'Successfuly Change Password'},
	CORRECTPASSWORD		: {'success':true,'message':'Please Enter Correct Password'},
	RESETPASSWORDSUCCESS: {'success':true,'message':'Reset password sucessfully'},
	MAIL_SEND	    	: {'success':true,'message':'Mail send sucessfully'},
	SUCCESSAPPLICATION 	: {'success':true,'message':'Sucessfully created application'},
	USERDELETE 	    	: {'success':true,'message':'User deleted sucessfully'},
	ADMINDELETE 	    : {'success':true,'message':'Admin deleted sucessfully'},
	APP 	 	    	: {'success':true,'message':'App deleted sucessfully'},
	APPUPDATE 	    	: {'success':true,'message':'App updated sucessfully'},
	APPNOTUPDATE    	: {'success':true,'message':'App not updated sucessfully'},
	NOTIFICATION 		: {'success':true,'message':'Successfully sent notification'},
	CREATEDSUCCESS 		: {'success':true,'message':'Created'},
	UPDATEDSUCCESS 		: {'success':true,'message':'Updated'},
	DELETEDSUCCESS 		: {'success':true,'message':'Deleted'},
	ACTIVE 				: {'success':true,'message':'Active'},



}

module.exports = message